"""empty message

Revision ID: f3ae7c9572b1
Revises: 01fdc9e86964
Create Date: 2019-04-05 19:46:01.611960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3ae7c9572b1'
down_revision = '01fdc9e86964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('attr1', sa.String(length=60), nullable=False))
    op.add_column('results', sa.Column('attr2', sa.String(length=60), nullable=False))
    op.add_column('results', sa.Column('attr3', sa.String(length=60), nullable=False))
    op.add_column('results', sa.Column('company_name', sa.String(length=60), nullable=False))
    op.add_column('results', sa.Column('ratio1', sa.Float(precision=6, asdecimal=4), nullable=False))
    op.add_column('results', sa.Column('ratio2', sa.Float(precision=6, asdecimal=4), nullable=False))
    op.add_column('results', sa.Column('ratio3', sa.Float(precision=6, asdecimal=4), nullable=False))
    op.drop_column('results', 'model_name')
    op.drop_column('results', 'accuracy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('accuracy', mysql.FLOAT(), nullable=False))
    op.add_column('results', sa.Column('model_name', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('results', 'ratio3')
    op.drop_column('results', 'ratio2')
    op.drop_column('results', 'ratio1')
    op.drop_column('results', 'company_name')
    op.drop_column('results', 'attr3')
    op.drop_column('results', 'attr2')
    op.drop_column('results', 'attr1')
    # ### end Alembic commands ###
