"""empty message

Revision ID: fe57538a130c
Revises: f3ae7c9572b1
Create Date: 2019-05-16 07:26:12.410648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe57538a130c'
down_revision = 'f3ae7c9572b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('algo1', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'algo1')
    # ### end Alembic commands ###
